language: python

python:
  - 2.7
  - 3.7
  - 3.8
  - pypy
  - pypy3

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
  - pip install poetry

script:
  - poetry install
  - pytest

after_success:
    - coveralls
